config/routes.rb
Refinery::Application.routes.draw do
  resources :testimonials, :only => [:index]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :testimonials do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base

  acts_as_indexed :fields => [
    :quote, :name, :company, :job_title, :website,
  ]
  
  validates_presence_of :quote
  validates_presence_of :name

  def flash_name
    "Quote by #{self.name}"
  end

  def self.random
    self.find :first, :offset => (Testimonial.count * rand).to_i
  end
end

app/controllers/admin/testimonials_controller.rb
class Admin::TestimonialsController < Admin::BaseController

  crudify :testimonial,
          :title_attribute => :flash_name

end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController

  before_filter :find_page

  def index
    @testimonials = Testimonial.paginate(
      :all,
      :order => "position ASC",
      :page => params[:page],
      :per_page => RefinerySetting.find_or_set(:testimonials_per_page, 10)
    )
    present(@page)
  end

protected

  def find_page
    @page = Page.find_by_link_url("/testimonials")
  end

end

app/helpers/testimonials_helper.rb
module TestimonialsHelper

  def display_page_testimonial_if_setup
    if @page.show_a_testimonial? && (random_testimonial = Testimonial.random)
      content_for :head, stylesheet_link_tag('testimonials')
      render :partial => '/testimonials/testimonial', :locals => {
        :testimonial => random_testimonial
      }
    end
  end

  def citation_line(t)
    [
      content_tag(:b, h(t.name)),
      h(t.job_title),
      website_or_company(t)
    ].reject{|o| o.blank?}.join(', ').sub(/,\s/, ': ')
  end

  def website_or_company(t)
    if t.website.blank?
      h(t.company)
    else
      content_tag(:a, h(t.company.blank? ? t.website : t.company), :href => h(t.website))
    end
  end
end

app/views/admin/testimonials/_form.html.erb
<% form_for [:admin, @testimonial] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
    :object => @testimonial,
    :include_object_name => true
  } %>

  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :quote -%>
    <%= f.text_area :quote, :rows => 10, :class => 'widest' -%>
  </div>
 
  <div class='field'>
    <%= f.label :company -%>
    <%= f.text_field :company, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :job_title -%>
    <%= f.text_field :job_title, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :website -%>
    <%= f.text_field :website, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :quoted_on -%>
    <%= f.date_select :quoted_on -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('admin.testimonials.testimonial.delete'),
                :delete_confirmation => t('shared.admin.delete.message', :title => @testimonial.name)
              } %>
<% end -%>

app/views/admin/testimonials/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'testimonial', :collection => @testimonials %>
</ul>
<%= render :partial => "/shared/admin/sortable_list", :locals => {:continue_reordering => (defined?(continue_reordering) ? continue_reordering : true)} %>

app/views/admin/testimonials/_testimonial.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(testimonial) -%>">
  <span class='title'>
    <span class='actions'>
      <%= link_to refinery_icon_tag("eye.png"), '#',
          :title => 'Toggle the display of this quote',
          :style => 'display:none;',
          :class => 'toggle_quote' %>
      <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_testimonial_path(testimonial),
           :title => t('.edit') %>
      <%= link_to refinery_icon_tag("delete.png"), admin_testimonial_path(testimonial),
          :class => "cancel confirm-delete",
          :title => t('.delete'),
          :'data-confirm' => t('shared.admin.delete.message', :title => testimonial.name),
          :'data-method' => :delete %>
    </span>

    <%= [content_tag(:b, h(testimonial.name)), h(testimonial.job_title), h(testimonial.company)].reject(&:blank?).join(", ").html_safe %>
    <span class="preview">&nbsp;</span>
    <div class="quote"><%= h(testimonial.quote) %></div>
  </span>
</li>

app/views/admin/testimonials/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/testimonials/index.html.erb
<% content_for :stylesheets do %>
  <style type="text/css">
    .quote {
      width: 100%;
    }
  </style>
<% end %>
<% content_for :javascripts do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.quote').hide();
      $('.toggle_quote').show().click(function(e){
        $(this).parents('.title').find('.quote').animate({opacity: 'toggle', height: 'toggle'}, 250);
        e.preventDefault();
      });
    });
  </script>
<% end %>
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
  <% end %>
  <% if @testimonials.any? %>
    <%= will_paginate @testimonials,
                       :previous_label => '&laquo;',
                       :next_label => '&raquo;' %>

    <%= render :partial => "sortable_list" %>

    <%= will_paginate @testimonials,
                       :previous_label => '&laquo;',
                       :next_label => '&raquo;' %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong>
          <%= t('.no_items_yet') %>
        </strong>
      <% else %>
        <%= t('shared.admin.search.no_results') %>
      <% end %>
    </p>
  <% end %>
</div>
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_testimonials_url
                  } %>
    </li>
    <li>
      <%= link_to t('.create_new'), new_admin_testimonial_url,
                   :class => "add_icon" %>
    </li>
  <% if !searching? and Testimonial.count > 1 %>
    <li>
      <%= link_to t('.reorder', :what => "Testimonials"),
                   admin_testimonials_url,
                   :id => "reorder_action",
                   :class => "reorder_icon" %>

      <%= link_to t('.reorder_done', :what => "Testimonials"),
                   admin_testimonials_url,
                   :id => "reorder_action_done",
                   :style => "display: none;",
                   :class => "reorder_icon" %>
    </li>
  <% end %>
  </ul>
</div>
<%= render :partial => "/shared/admin/make_sortable",
            :locals => {
              :tree => false
            } if !searching? and Testimonial.count > 1 %>

app/views/admin/testimonials/new.html.erb
<%= render :partial => "form" %>

app/views/testimonials/_testimonial.html.erb
<div class="testimonial">
  <blockquote>
    <p><%= raw testimonial.quote %></p>
    <p><cite><%= raw citation_line(testimonial) %></cite></p>
  </blockquote>
</div>

app/views/testimonials/index.html.erb
<% content_for :body_content_left do %>
  <%= will_paginate @testimonials %>

  <div id="testimonials">
    <%= render :partial => 'testimonial', :collection => @testimonials %>
  </div>

  <%= will_paginate @testimonials %>
<% end %>

<% content_for :body_content_right do %>
  <%= @page[:side_body]  %>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/testimonials/show.html.erb
<% content_for :body_content_title do %>
  <%= @testimonial.name %>
<% end %>

<% content_for :body_content_left do %>
  
  <section>
    <h1>Quote</h1>
<p>    <%=raw @testimonial.quote %>
</p>
  </section>
  
  <section>
    <h1>Name</h1>
<p>    <%=raw @testimonial.name %>
</p>
  </section>
  
  <section>
    <h1>Company</h1>
<p>    <%=raw @testimonial.company %>
</p>
  </section>
  
  <section>
    <h1>Job Title</h1>
<p>    <%=raw @testimonial.job_title %>
</p>
  </section>
  
  <section>
    <h1>Website</h1>
<p>    <%=raw @testimonial.website %>
</p>
  </section>
  
  <section>
    <h1>Quoted On</h1>
<p>    <%=raw @testimonial.quoted_on %>
</p>
  </section>
  
  <section>
    <h1>Position</h1>
<p>    <%=raw @testimonial.position %>
</p>
  </section>
  
<% end %>

<% content_for :body_content_right do %>
<aside>
  <h2><%= t('.other') %></h2>
  <ul id="testimonials">
    <% @testimonials.each do |testimonial| %>
      <li>
        <%= link_to testimonial.name, testimonial_url(testimonial) %>
      </li>
    <% end %>
  </ul>
</aside>
<% end %>

<%= render :partial => "/shared/content_page" %>